### ISSUE TITLE
ba

### ISSUE THREAD

**Issue by nor1c** [ratnoriyadi/Geratno#1]
ba

**Comment by ratnoriyadi** [comment]
ke kok

**Comment by nor1c** [comment]
push dong project lu, buat belajar guahh

**Comment by ratnoriyadi** [comment]
<?php

?>

<!DOCTYPE html>
<html>
<head>

```
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons"
```

rel="stylesheet">
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"
 media="screen,projection"/>
      <meta name="viewport" content="width=device-width,
initial-scale=1.0"/>

<meta charset="utf-8">
<title>Register</title>
<link rel="stylesheet" href="css/style.css" />
</head>
<body>
<?php
require('db.php');

```
if (isset($_REQUEST['username'])){
$nama_lengkap = stripcslashes($_REQUEST['nama_lengkap']);
$nama_lengkap = mysqli_real_escape_string($con,$nama_lengkap);
```

$username = stripslashes($_REQUEST['username']);
$username = mysqli_real_escape_string($con,$username);

$kode = stripslashes($_REQUEST['kode']);
$kode = mysqli_real_escape_string($con,$kode);

$password = stripslashes($_REQUEST['password']);
$password = mysqli_real_escape_string($con,$password);

```
    $kota_asal = stripcslashes($_REQUEST['kota_asal']);
    $kota_asal = mysqli_real_escape_string($con,$kota_asal);
```

$trn_date = date("Y-m-d H:i:s");
        $query = "INSERT into `users` (nama_lengkap, username, password,
kode, kota_asal, trn_date)
         VALUES ('$nama_lengkap', '$username', '".md5($password)."',
'$kode', '$kota_asal', '$trn_date')";

```
    $result = mysqli_query($con,$query);

    if($result){
        echo "<div class='form'><h5> Register Sukses</h5><br/> Klik di
```

sini untuk <a href='login.php'>Login</a></div>";
        }
    }else{
?>

<div class="formregis">
<center><b><h6>Register</h6></center><br>
<form name="registration" action="" method="post">
<center><input type="text" name="nama_lengkap" placeholder="Nama Lengkap"
required /><p></center>
<center><input type="text" name="username" placeholder="Username" required
/><p></center>
<center><input type="password" name="password" placeholder="Password"
required /><p></center>
<center><input type="text" name="kode" placeholder="Kode Voucher" required
/><p></center>
<center><input type="text" name="kota_asal" placeholder="Kota Asal"
required /><p></center>
<center><input type="submit" name="submit" value="Register" /></center>
</form>
<br /><br />
</div>

<?php } ?>

 <script type="text/javascript" src="
https://code.jquery.com/jquery-2.1.1.min.js"></script>
 <script type="text/javascript" src="js/materialize.min.js"></script>

</body>
</html>

2016-10-13 17:15 GMT+07:00 Ahmad Fauzi notifications@github.com:

**Comment by nor1c** [comment]
itu select optionnya mana, ga ada

**Comment by ratnoriyadi** [comment]
http://www.penerbitduta.com/#.WUTi73O2MWT.gmail
